export const BOILER_TESTS = [
  {
    key: 'ph',
    label: 'pH',
    system: 'boiler',
    unit: '',
    target: '8.5 – 10.5',
    icon: '⚗',
    color: 'blue',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Universal_indicator_paper.jpg/320px-Universal_indicator_paper.jpg',
    description: 'pH measures how acidic or alkaline the boiler water is. Proper pH prevents corrosion of metal surfaces and scale buildup.',
    testKit: 'pH drop test kit (Taylor K-1000) or digital pH meter',
    procedure: [
      'Collect a fresh water sample — run the tap 30 seconds first to flush the line',
      'Fill the test tube or beaker to the marked line (typically 10 mL)',
      'Add 3–5 drops of pH indicator solution, cap and invert gently',
      'Compare the color immediately to the color chart included in your kit',
      'If using a digital meter: rinse probe with distilled water, submerge tip, wait for a stable reading',
      'Record the result immediately in FacilityH2O',
    ],
    ifHigh: {
      title: 'pH Too High (above 10.5)',
      steps: [
        'Increase blowdown frequency to dilute the concentrated water',
        'Verify chemical feed pump is not over-dosing caustic or alkalinity builder',
        'Check makeup water quality — high hardness water can drive pH up',
        'Contact your water treatment vendor (Nalco/Diversey) to adjust chemical dosing',
        'Do NOT add acid directly to the boiler without vendor guidance',
      ],
    },
    ifLow: {
      title: 'pH Too Low (below 8.5)',
      steps: [
        'Check chemical feed pump operation — may be underdosing pH builder',
        'Verify chemical drum level — may be out of product',
        'Inspect for makeup water infiltration or CO2 contamination',
        'Add approved pH booster per your treatment program dosage chart',
        'Notify your water treatment vendor if pH is below 8.0 — corrosion risk is significant',
        'Increase testing frequency to every shift until resolved',
      ],
    },
  },
  {
    key: 'phosphate',
    label: 'Phosphate',
    system: 'boiler',
    unit: 'ppm',
    target: '20 – 60 ppm',
    icon: '⚗️',
    color: 'purple',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Phosphate_test_kit.jpg/320px-Phosphate_test_kit.jpg',
    description: 'Phosphate acts as a scale inhibitor and pH buffer in boiler water. It reacts with hardness minerals before they can deposit on heat transfer surfaces.',
    testKit: 'Phosphate test kit (Hach or Taylor) — colorimetric drop or tablet test',
    procedure: [
      'Collect a cooled water sample (boiler water should be below 40°C before testing)',
      'Fill the comparator tube to the marked line (usually 5 mL)',
      'Add the phosphate reagent tablet or the specified drops, mix thoroughly',
      'Wait the required reaction time (usually 2–3 minutes)',
      'Compare the resulting color to the color disc or chart',
      'Record result in ppm immediately',
    ],
    ifHigh: {
      title: 'Phosphate Too High (above 60 ppm)',
      steps: [
        'Reduce chemical feed rate on the phosphate treatment pump',
        'Increase blowdown to reduce concentration',
        'Check if the wrong chemical is being fed or if the product concentration changed',
        'Notify water treatment vendor — sustained high phosphate can cause sludge buildup',
      ],
    },
    ifLow: {
      title: 'Phosphate Too Low (below 20 ppm)',
      steps: [
        'Check chemical feed pump — verify it is running and properly primed',
        'Inspect chemical drum level — may be empty',
        'Verify feed rate settings against the treatment program specification',
        'Manually dose approved phosphate product if authorized by vendor',
        'Increase blowdown frequency temporarily to reset the system, then refeed',
        'If below 10 ppm, contact vendor immediately — scale risk is high',
      ],
    },
  },
  {
    key: 'sulfite',
    label: 'Sulfite (Oxygen Scavenger)',
    system: 'boiler',
    unit: 'ppm',
    target: '20 – 80 ppm',
    icon: '[FOAM]',
    color: 'green',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Colorimetric_test.jpg/320px-Colorimetric_test.jpg',
    description: 'Sulfite removes dissolved oxygen from boiler feedwater. Oxygen causes pitting corrosion of boiler tubes — one of the most destructive forms of boiler damage.',
    testKit: 'Sulfite test kit (Hach or Taylor) — titration-based',
    procedure: [
      'Collect a fresh sample — test IMMEDIATELY, oxygen exposure will degrade sulfite levels rapidly',
      'Fill the titration tube to the specified volume (usually 25 mL)',
      'Add indicator drops (solution will turn blue/purple)',
      'Add potassium iodate titrant one drop at a time, swirling between drops',
      'Stop when the color changes from blue to colorless (endpoint)',
      'Calculate: number of drops × titration factor = sulfite in ppm',
    ],
    ifHigh: {
      title: 'Sulfite Too High (above 80 ppm)',
      steps: [
        'Reduce chemical feed pump rate by 10–15%',
        'High sulfite rarely causes equipment damage, but wastes chemical',
        'Check if system pressure or temperature changes are requiring less oxygen scavenger',
        'Recalibrate feed rate with vendor',
      ],
    },
    ifLow: {
      title: 'Sulfite Too Low (below 20 ppm)',
      steps: [
        'URGENT: Low sulfite means dissolved oxygen is present — corrosion is occurring',
        'Check chemical feed pump immediately — verify operation',
        'Check drum level — may be out of product',
        'Inspect feedwater deaerator (if present) for proper operation',
        'Manually dose sulfite treatment if authorized — follow vendor dosage chart',
        'If consistently below 10 ppm, shut down and notify vendor and facility director',
      ],
    },
  },
  {
    key: 'hardness',
    label: 'Hardness',
    system: 'boiler',
    unit: 'ppm',
    target: '0 ppm (zero — anything above is a problem)',
    icon: '[CRYSTAL]',
    color: 'yellow',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Hard_water_glass.jpg/320px-Hard_water_glass.jpg',
    description: 'Hardness (calcium and magnesium) causes scale on boiler heat transfer surfaces. Scale is a major cause of reduced efficiency, overheating, and boiler tube failure.',
    testKit: 'Hardness test kit (Hach or Taylor) — EDTA titration',
    procedure: [
      'Fill titration tube to 25 mL with water sample',
      'Add 5 drops of hardness buffer solution',
      'Add 2–3 drops of indicator (solution turns red/pink)',
      'Add EDTA titrant one drop at a time, swirling between each drop',
      'Count drops until solution turns blue (endpoint)',
      'Each drop = 1 ppm hardness (for a 25 mL sample)',
    ],
    ifHigh: {
      title: 'Hardness Too High (above 5 ppm)',
      steps: [
        'Check water softener operation — regeneration may have failed',
        'Inspect softener salt level — may need recharging',
        'Increase blowdown rate immediately to reduce hardness concentration',
        'Verify softener bypass valve is fully closed',
        'Notify water treatment vendor — scale deposits may have already begun',
        'If softener is offline, reduce boiler load until repaired',
      ],
    },
    ifLow: {
      title: 'Hardness at Zero — IDEAL ✓',
      steps: [
        'Zero hardness is the target — this is the only acceptable result',
        'Continue normal monitoring schedule',
        'Verify softener is functioning properly to maintain this result',
      ],
    },
  },
  {
    key: 'conductivity',
    label: 'Conductivity',
    system: 'boiler',
    unit: 'µS/cm',
    target: '0 – 3,500 µS/cm',
    icon: '↯',
    color: 'orange',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Conductivity_meter.jpg/320px-Conductivity_meter.jpg',
    description: 'Conductivity measures the total dissolved solids concentration in boiler water. High conductivity leads to foaming, carryover, and increased risk of corrosion.',
    testKit: 'Conductivity meter (handheld digital, Hach or similar)',
    procedure: [
      'Rinse the conductivity probe with distilled water',
      'Collect a fresh water sample, allow to cool to room temperature if needed',
      'Submerge the probe tip fully in the sample',
      'Wait for the reading to stabilize (5–10 seconds)',
      'Record the value in µS/cm',
      'Rinse the probe again after use and store per manufacturer instructions',
    ],
    ifHigh: {
      title: 'Conductivity Too High (above 3,500 µS/cm)',
      steps: [
        'Increase blowdown frequency immediately — this is the primary corrective action',
        'Check automatic blowdown controller setpoints if installed',
        'Verify makeup water quality — high TDS source water will concentrate faster',
        'Reduce steam demand temporarily if possible',
        'Notify water treatment vendor if conductivity exceeds 4,000 µS/cm',
      ],
    },
    ifLow: {
      title: 'Conductivity Too Low (significantly below range)',
      steps: [
        'May indicate excessive blowdown — reducing unnecessarily wastes water and energy',
        'Recalibrate blowdown controller if automated',
        'Review blowdown schedule with water treatment vendor',
      ],
    },
  },
  {
    key: 'alkalinity',
    label: 'Alkalinity (M-Alkalinity)',
    system: 'boiler',
    unit: 'ppm',
    target: '100 – 700 ppm',
    icon: '[WAVE]',
    color: 'teal',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Titration_alkalinity.jpg/320px-Titration_alkalinity.jpg',
    description: 'M-Alkalinity measures bicarbonate, carbonate, and hydroxide alkalinity. It buffers pH and prevents acidic corrosion, but excess causes scale and foaming.',
    testKit: 'M-Alkalinity titration kit (Hach or Taylor)',
    procedure: [
      'Fill the titration tube to 100 mL with a fresh water sample',
      'Add 2–3 drops of M-alkalinity indicator (solution turns green)',
      'Add sulfuric acid titrant one drop at a time, swirling after each drop',
      'Count the drops until the color changes from green to red/pink',
      'Multiply the drop count by the titration factor (typically 10) = ppm M-alkalinity',
    ],
    ifHigh: {
      title: 'Alkalinity Too High (above 700 ppm)',
      steps: [
        'Increase blowdown frequency to dilute',
        'Reduce alkalinity builder in chemical feed if applicable',
        'High alkalinity can cause foaming and carryover — check steam quality',
        'Inspect deaerator and steam traps for carryover signs',
        'Contact vendor to adjust chemical program',
      ],
    },
    ifLow: {
      title: 'Alkalinity Too Low (below 100 ppm)',
      steps: [
        'Increase chemical feed of alkalinity builder per vendor dosage chart',
        'Check makeup water alkalinity — source water may be naturally low',
        'Low alkalinity combined with low pH is a serious corrosion risk — escalate immediately',
        'Notify water treatment vendor for program adjustment',
      ],
    },
  },
  {
    key: 'tds',
    label: 'TDS (Total Dissolved Solids)',
    system: 'boiler',
    unit: 'ppm',
    target: '0 – 3,000 ppm',
    icon: '⊕',
    color: 'gray',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/TDS_meter.jpg/320px-TDS_meter.jpg',
    description: 'TDS is closely related to conductivity and measures all dissolved minerals in the water. High TDS increases scale and corrosion risk.',
    testKit: 'TDS meter (digital handheld) or calculate from conductivity reading',
    procedure: [
      'Use a calibrated digital TDS meter',
      'Rinse probe with distilled water',
      'Submerge probe in sample, wait for stable reading',
      'Record value in ppm',
      'TDS can also be estimated: TDS (ppm) ≈ Conductivity (µS/cm) × 0.64',
    ],
    ifHigh: {
      title: 'TDS Too High (above 3,000 ppm)',
      steps: [
        'Increase blowdown — same corrective action as high conductivity',
        'Check makeup water quality',
        'Verify blowdown controller operation',
        'Notify vendor if above 3,500 ppm',
      ],
    },
    ifLow: {
      title: 'TDS Very Low',
      steps: [
        'Generally not a concern operationally',
        'May indicate over-blowdown — review schedule to conserve water and energy',
      ],
    },
  },
  {
    key: 'amine',
    label: 'Amine Residual (Steam/Condensate Treatment)',
    system: 'boiler',
    unit: 'ppm',
    target: '0 – 10 ppm',
    icon: '[AIR]',
    color: 'pink',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Steam_condensate.jpg/320px-Steam_condensate.jpg',
    description: 'Amine is a neutralizing or filming amine added to protect the steam and condensate return system from carbonic acid corrosion.',
    testKit: 'Amine test kit (specific to your amine product — check with vendor)',
    procedure: [
      'Collect a condensate return sample (not boiler water)',
      'Follow the test kit instructions specific to your amine product',
      'Most amine tests are colorimetric — add reagent, compare to color chart',
      'Record result in ppm',
    ],
    ifHigh: {
      title: 'Amine Too High (above 10 ppm)',
      steps: [
        'Reduce amine feed pump rate by 10–15%',
        'Excess amine is not immediately harmful but increases chemical cost',
        'Recheck in next shift to confirm reduction',
      ],
    },
    ifLow: {
      title: 'Amine Too Low (below recommended level)',
      steps: [
        'Increase amine feed pump rate per vendor recommendation',
        'Inspect condensate return lines for corrosion products (rusty or dark condensate)',
        'Check for condensate return system leaks that may be diluting amine',
        'Notify vendor if condensate is visibly discolored',
      ],
    },
  },
];

export const CHILLED_TESTS = [
  {
    key: 'ph',
    label: 'pH',
    system: 'chilled',
    unit: '',
    target: '7.5 – 9.5',
    icon: '⚗',
    color: 'blue',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Universal_indicator_paper.jpg/320px-Universal_indicator_paper.jpg',
    description: 'pH in chilled water systems prevents corrosion of copper, steel, and aluminum components. Lower pH than boiler systems due to different metallurgy.',
    testKit: 'pH test kit or digital meter',
    procedure: [
      'Collect sample from the chilled water return line (not the supply)',
      'Test immediately or within 15 minutes of collection',
      'Add pH indicator drops or use digital meter',
      'Compare to chart or read digital display',
      'Record result',
    ],
    ifHigh: {
      title: 'pH Too High (above 9.5)',
      steps: [
        'Check inhibitor dosing — some inhibitors raise pH significantly',
        'Increase bleed-off to dilute',
        'Notify water treatment vendor to adjust program',
      ],
    },
    ifLow: {
      title: 'pH Too Low (below 7.5)',
      steps: [
        'URGENT: pH below 7.5 causes rapid corrosion in chilled water systems',
        'Check inhibitor levels — low inhibitor often correlates with pH drop',
        'Increase inhibitor dosing per vendor recommendation',
        'Inspect for acidic contamination (process leaks, CO2 ingress)',
        'Notify vendor immediately if pH is below 7.0',
      ],
    },
  },
  {
    key: 'inhibitor',
    label: 'Inhibitor Level',
    system: 'chilled',
    unit: 'ppm',
    target: '50 – 300 ppm',
    icon: '⬡️',
    color: 'green',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Corrosion_inhibitor.jpg/320px-Corrosion_inhibitor.jpg',
    description: 'Corrosion inhibitors form a protective film on metal surfaces, preventing oxidation. They are the primary protection for chilled water system metals.',
    testKit: 'Inhibitor test kit — specific to your product (Molybdate, Tolyltriazole, or proprietary). Check with your vendor (Nalco, Diversey, ChemTreat).',
    procedure: [
      'Use the test kit provided by your water treatment vendor',
      'Most inhibitor tests are colorimetric — add reagent to sample, compare color',
      'Follow the exact procedure on the test kit instructions',
      'Record result in ppm',
      'If using a proprietary tracer-based test, use the vendor-supplied meter',
    ],
    ifHigh: {
      title: 'Inhibitor Too High (above 300 ppm)',
      steps: [
        'Reduce chemical feed pump rate',
        'Increase bleed-off to dilute system',
        'High inhibitor wastes chemical but rarely causes damage',
        'Contact vendor to recalibrate dosing',
      ],
    },
    ifLow: {
      title: 'Inhibitor Too Low (below 50 ppm)',
      steps: [
        'Increase chemical feed pump rate immediately',
        'Check drum level — may be empty',
        'Manually dose inhibitor if authorized by vendor',
        'Inspect system for leaks that may be causing loss',
        'If below 25 ppm, notify vendor and facility director — corrosion is occurring',
        'Increase testing frequency to every shift until resolved',
      ],
    },
  },
  {
    key: 'hardness',
    label: 'Hardness',
    system: 'chilled',
    unit: 'ppm',
    target: '0 – 200 ppm',
    icon: '[CRYSTAL]',
    color: 'yellow',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Hard_water_glass.jpg/320px-Hard_water_glass.jpg',
    description: 'Some hardness is acceptable in chilled water (unlike boiler systems) as the lower temperatures reduce scale formation risk. However, high hardness still reduces inhibitor effectiveness.',
    testKit: 'Hardness test kit (Hach or Taylor) — EDTA titration',
    procedure: [
      'Fill titration tube to 25 mL',
      'Add buffer and indicator (turns red)',
      'Add EDTA titrant drop by drop until blue',
      'Each drop = 1 ppm for a 25 mL sample',
    ],
    ifHigh: {
      title: 'Hardness Too High (above 200 ppm)',
      steps: [
        'Increase bleed-off to dilute',
        'Check makeup water source quality',
        'Notify vendor — scale can form on heat exchanger surfaces at elevated hardness',
      ],
    },
    ifLow: {
      title: 'Hardness Very Low or Zero',
      steps: [
        'Acceptable — no action needed',
        'Maintain normal monitoring schedule',
      ],
    },
  },
  {
    key: 'iron',
    label: 'Iron',
    system: 'chilled',
    unit: 'ppm',
    target: '0 – 2 ppm',
    icon: '',
    color: 'red',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Iron_corrosion.jpg/320px-Iron_corrosion.jpg',
    description: 'Elevated iron indicates active corrosion of ferrous metal components (pipes, valves, pumps). Even small amounts can cause fouling of heat exchanger surfaces.',
    testKit: 'Iron test kit (Hach or Taylor) — colorimetric',
    procedure: [
      'Fill test tube to marked line with water sample',
      'Add iron reagent tablet or drops — solution will turn orange/red if iron is present',
      'Wait reaction time (2–3 minutes)',
      'Compare to color chart',
      'Record result in ppm',
    ],
    ifHigh: {
      title: 'Iron Too High (above 2 ppm)',
      steps: [
        'URGENT: Elevated iron = active corrosion in the system',
        'Verify inhibitor level immediately — low inhibitor is the most common cause',
        'Check pH — acidic conditions accelerate iron corrosion',
        'Inspect system for visible rust or discoloration at drain points',
        'Notify water treatment vendor and facility director',
        'Consider system flush and chemical cleaning if iron exceeds 5 ppm',
      ],
    },
    ifLow: {
      title: 'Iron at Zero or Near Zero',
      steps: [
        'Ideal result — system is well-protected',
        'Continue normal monitoring',
      ],
    },
  },
  {
    key: 'bacteria',
    label: 'Bacteria (Dip Slide)',
    system: 'chilled',
    unit: 'CFU/mL',
    target: '0 – 1,000 CFU/mL',
    icon: '⌬',
    color: 'purple',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Bacteria_dipslide.jpg/320px-Bacteria_dipslide.jpg',
    description: 'Bacteria in chilled water systems can cause biofouling, Legionella risk (if connected to domestic systems), and accelerated corrosion. Regular dip slide testing is a Joint Commission requirement.',
    testKit: 'Dip slide test (Merck Millipore or equivalent) — requires 48–72 hour incubation',
    procedure: [
      'Open dip slide package, remove slide without touching the agar surface',
      'Submerge slide in water sample for 10 seconds',
      'Drain excess water, do not rinse',
      'Replace in the vial loosely (do not seal tightly)',
      'Incubate upright at room temperature (20–25°C) for 48–72 hours',
      'After incubation, compare colony growth to the reference chart',
      'Record result in CFU/mL',
    ],
    ifHigh: {
      title: 'Bacteria Too High (above 1,000 CFU/mL)',
      steps: [
        'URGENT: Elevated bacteria requires immediate biocide treatment',
        'Notify water treatment vendor — they should provide an emergency shock dose',
        'Do NOT ignore high bacteria counts — Legionella risk must be managed',
        'Verify biocide feed system is operating correctly',
        'Document corrective action per Joint Commission Water Management Plan',
        'Retest within 7 days after treatment to confirm reduction',
        'If counts above 100,000 CFU/mL, notify facility director and consider system isolation',
      ],
    },
    ifLow: {
      title: 'Bacteria Low (below 1,000 CFU/mL)',
      steps: [
        'System is well-controlled — continue routine monitoring',
        'Maintain regular biocide dosing schedule per treatment program',
      ],
    },
  },
];

// !️ TYPICAL PROCEDURES & RANGES — verify against your water treatment program and equipment manuals.
export const COOLING_TOWER_TESTS = [
  {
    key: 'ph', label: 'pH', system: 'cooling_tower', unit: '', target: '8.0 – 9.0', icon: '⚗', color: 'blue',
    description: 'pH of open recirculating cooling water. Proper pH limits corrosion and scale while keeping biocide effective.',
    testKit: 'Digital pH meter or pH test strips rated for cooling water',
    procedure: [
      'Draw a sample from the tower basin or recirculation line — run briefly to flush',
      'Rinse the pH probe with distilled water and submerge the tip',
      'Wait for a stable reading; if using strips, compare to the chart at the stated time',
      'Record the result immediately in FacilityH2O',
    ],
    ifHigh: { title: 'pH Too High (above 9.0)', steps: [
      'Increase bleed/blowdown to dilute concentrated water',
      'Verify acid feed (if used) is operating and not underdosing',
      'Check makeup water alkalinity',
      'Contact your water treatment vendor before manually adjusting acid feed',
    ]},
    ifLow: { title: 'pH Too Low (below 8.0)', steps: [
      'Verify acid feed is not overdosing',
      'Check for process contamination or flue-gas absorption',
      'Confirm inhibitor program is intact — low pH accelerates corrosion',
      'Notify your water treatment vendor',
    ]},
  },
  {
    key: 'free_chlorine', label: 'Free Chlorine', system: 'cooling_tower', unit: 'ppm', target: '0.2 – 1.0 ppm', icon: '⊕', color: 'green',
    description: 'Oxidizing biocide residual. Maintains microbiological control and helps manage Legionella risk in the tower.',
    testKit: 'DPD free-chlorine test kit (drop or colorimeter)',
    procedure: [
      'Collect a fresh basin sample',
      'Add DPD reagent per kit instructions and mix',
      'Read color immediately (chlorine dissipates fast) against the chart or meter',
      'Record result in ppm',
    ],
    ifHigh: { title: 'Free Chlorine Too High (above 1.0 ppm)', steps: [
      'Reduce biocide feed rate',
      'High oxidant can accelerate corrosion and degrade inhibitor — do not sustain',
      'Verify feed timer/pump settings',
    ]},
    ifLow: { title: 'Free Chlorine Too Low (below 0.2 ppm)', steps: [
      'URGENT for Legionella control — low residual means inadequate microbial control',
      'Verify biocide feed system and product level',
      'Increase feed per program; consider a shock dose per vendor guidance',
      'Document corrective action per the Water Management Plan and retest',
    ]},
  },
  {
    key: 'conductivity', label: 'Conductivity', system: 'cooling_tower', unit: 'µS/cm', target: '1,000 – 3,000 µS/cm', icon: '↯', color: 'amber',
    description: 'Measures dissolved solids / cycles of concentration. Controls scaling and bleed-off rate.',
    testKit: 'Handheld conductivity meter',
    procedure: ['Collect a basin sample','Rinse and submerge the conductivity probe','Wait for a stable reading','Record in µS/cm'],
    ifHigh: { title: 'Conductivity Too High (above 3,000)', steps: ['Increase bleed/blowdown','Verify the conductivity controller and bleed valve are functioning','Check makeup water quality','Notify vendor if it stays high — scaling risk'] },
    ifLow: { title: 'Conductivity Too Low (below 1,000)', steps: ['May indicate excessive bleed wasting water and chemical','Verify bleed valve is not stuck open','Confirm controller setpoint'] },
  },
  {
    key: 'inhibitor', label: 'Inhibitor/Molybdate', system: 'cooling_tower', unit: 'ppm', target: '8 – 12 ppm', icon: '⚗️', color: 'purple',
    description: 'Corrosion inhibitor residual (often tracked via molybdate). Confirms the treatment program is being maintained.',
    testKit: 'Molybdate test kit per your program',
    procedure: ['Collect a basin sample','Add reagents per kit and wait the reaction time','Compare color to chart','Record in ppm'],
    ifHigh: { title: 'Inhibitor Too High (above 12 ppm)', steps: ['Reduce inhibitor feed','Check for feed pump overdosing','Notify vendor — sustained overfeed wastes chemical'] },
    ifLow: { title: 'Inhibitor Too Low (below 8 ppm)', steps: ['Corrosion protection is inadequate','Verify inhibitor feed pump and product level','Increase feed per program chart','Notify vendor'] },
  },
  {
    key: 'hardness', label: 'Hardness', system: 'cooling_tower', unit: 'ppm', target: 'Per program (≤ 400 ppm typical)', icon: '[CRYSTAL]', color: 'cyan',
    description: 'Calcium/magnesium hardness in the recirculating water. High hardness drives scale on heat-transfer surfaces.',
    testKit: 'Hardness titration test kit',
    procedure: ['Collect a basin sample','Titrate per kit instructions to the color endpoint','Calculate hardness from titrant used','Record in ppm'],
    ifHigh: { title: 'Hardness Too High (above program limit)', steps: ['Increase bleed/blowdown','Verify softener (if equipped on makeup) is functioning','Check scale inhibitor feed','Notify vendor'] },
    ifLow: { title: 'Hardness Low', steps: ['Generally acceptable — continue monitoring','Confirm makeup softener is not over-softening if that is a concern'] },
  },
  {
    key: 'bacteria', label: 'Bacteria (Dip Slide)', system: 'cooling_tower', unit: 'CFU/mL', target: '< 10,000 CFU/mL', icon: '⌬', color: 'red',
    description: 'Microbiological activity in the tower. Critical for Legionella risk management.',
    testKit: 'Dip slide (paddle tester) with incubation',
    procedure: ['Dip the paddle in a fresh basin sample','Replace in its tube and incubate 48–72 h at room temperature','Compare growth to the reference chart','Record in CFU/mL'],
    ifHigh: { title: 'Bacteria Too High (above 10,000 CFU/mL)', steps: ['URGENT: elevated counts require immediate biocide action','Notify vendor for an emergency shock dose','Verify biocide feed is operating','Document per the Water Management Plan and retest within days','Escalate to facility director at very high counts'] },
    ifLow: { title: 'Bacteria Controlled', steps: ['System is well controlled — continue routine biocide and monitoring'] },
  },
];

export const CONDENSATE_TESTS = [
  {
    key: 'ph', label: 'pH', system: 'condensate', unit: '', target: '7.5 – 9.0', icon: '⚗', color: 'blue',
    description: 'pH of returning steam condensate. Low pH (carbonic acid) corrodes condensate piping; amines are fed to control it.',
    testKit: 'pH meter or strips',
    procedure: ['Collect a cooled condensate sample','Measure pH with a rinsed probe or strip','Record immediately'],
    ifHigh: { title: 'pH Too High (above 9.0)', steps: ['Verify amine feed is not overdosing','Check for caustic carryover from the boiler','Notify vendor'] },
    ifLow: { title: 'pH Too Low (below 7.5)', steps: ['Carbonic acid corrosion risk — verify neutralizing amine feed','Check amine product level and feed pump','Inspect for air in-leakage adding CO2','Notify vendor — sustained low pH damages condensate lines'] },
  },
  {
    key: 'iron', label: 'Iron', system: 'condensate', unit: 'ppm', target: '< 1.0 ppm', icon: '', color: 'amber',
    description: 'Dissolved iron indicates corrosion of condensate piping. Rising iron is an early corrosion warning.',
    testKit: 'Iron test kit (colorimetric)',
    procedure: ['Collect a condensate sample','Add iron reagents per kit and wait reaction time','Compare color to chart or read on colorimeter','Record in ppm'],
    ifHigh: { title: 'Iron Too High (above 1.0 ppm)', steps: ['Indicates active condensate corrosion','Verify and likely increase neutralizing/filming amine feed','Investigate low-pH areas of the condensate system','Notify vendor and document'] },
    ifLow: { title: 'Iron Low', steps: ['Good — corrosion under control. Continue monitoring.'] },
  },
  {
    key: 'hardness', label: 'Hardness', system: 'condensate', unit: 'ppm', target: '0 ppm (none detectable)', icon: '', color: 'red',
    description: 'Hardness in returning condensate is a contamination signal — it points to raw-water or cooling-water in-leakage into the steam/condensate loop. Clean condensate carries essentially no hardness, so any detectable reading matters.',
    testKit: 'Hardness titration kit or test strips',
    procedure: ['Collect a cooled condensate return sample (not boiler water)','Run the hardness test per kit (titration drops or strip)','Record in ppm — note that any detectable hardness is significant'],
    ifHigh: { title: 'Hardness Detected (target is 0)', steps: ['Indicates in-leakage of raw or cooling water into the condensate','Identify the contaminated return line and isolate it if possible','Protect the boiler — hardness carryover causes scale; verify softener/feedwater hardness too','Notify vendor; heavily contaminated condensate may need to be dumped rather than returned'] },
    ifLow: { title: 'No Hardness (good)', steps: ['Condensate is clean — continue monitoring each shift.'] },
  },
  {
    key: 'conductivity', label: 'Conductivity', system: 'condensate', unit: 'µS/cm', target: '0 – 100 µS/cm', icon: '↯', color: 'green',
    description: 'High condensate conductivity signals contamination or carryover. Clean condensate should be very low.',
    testKit: 'Conductivity meter',
    procedure: ['Collect a condensate sample','Measure with a rinsed conductivity probe','Record in µS/cm'],
    ifHigh: { title: 'Conductivity Too High (above 100)', steps: ['Suspect process contamination or boiler carryover','Identify and isolate the contaminated return if possible','Notify vendor — contaminated condensate may need to be dumped'] },
    ifLow: { title: 'Conductivity Low', steps: ['Clean condensate — continue monitoring'] },
  },
  {
    key: 'amine', label: 'Amine Residual', system: 'condensate', unit: 'ppm', target: '0 – 10 ppm (per program)', icon: '⚗️', color: 'purple',
    description: 'Neutralizing amine residual confirming corrosion protection is reaching the condensate system.',
    testKit: 'Amine/neutralizing test per program',
    procedure: ['Collect a condensate sample','Run the amine test per kit instructions','Record in ppm'],
    ifHigh: { title: 'Amine Too High', steps: ['Reduce amine feed','Check feed pump settings','Notify vendor'] },
    ifLow: { title: 'Amine Too Low', steps: ['Condensate is under-protected — increase amine feed per program','Verify product level and pump operation','Notify vendor'] },
  },
];

export const SOFTENER_TESTS = [
  {
    key: 'hardness', label: 'Hardness', system: 'softener', unit: 'ppm', target: '0 ppm (soft)', icon: '[CRYSTAL]', color: 'cyan',
    description: 'Outlet hardness of a water softener. Properly regenerated softeners should produce zero hardness. Any hardness means breakthrough.',
    testKit: 'Hardness test kit (drop titration) or hardness test strips',
    procedure: [
      'Collect a sample from the SOFTENER OUTLET (treated side)',
      'Run the hardness test per kit — titrate to the endpoint or read the strip',
      'A properly working softener reads 0 ppm (zero hardness)',
      'Record the result immediately',
    ],
    ifHigh: { title: 'Hardness Detected (above 0 ppm — breakthrough)', steps: [
      'Softener is in breakthrough — it is passing hard water',
      'Check salt level in the brine tank and refill if low',
      'Verify the softener regenerated on schedule (check the control valve / timer)',
      'Confirm the unit is not stuck in bypass',
      'Manually initiate a regeneration if needed',
      'If hardness persists after regeneration, inspect resin and notify your water treatment vendor',
      'Downstream boilers/towers are at scale risk until resolved — increase their monitoring',
    ]},
    ifLow: { title: 'Zero Hardness (soft — correct)', steps: ['Softener is working correctly — continue routine salt checks and monitoring'] },
  },
  {
    key: 'conductivity', label: 'Conductivity', system: 'softener', unit: 'µS/cm', target: 'Per source water', icon: '↯', color: 'amber',
    description: 'Softeners exchange hardness for sodium and do not significantly change conductivity. Tracked as a reference/sanity check.',
    testKit: 'Conductivity meter',
    procedure: ['Collect a softener outlet sample','Measure with a rinsed probe','Record in µS/cm'],
    ifHigh: { title: 'Conductivity Higher Than Expected', steps: ['Compare to incoming source water','A large jump can indicate over-salting or a brine valve issue','Verify regeneration settings'] },
    ifLow: { title: 'Conductivity Normal', steps: ['Consistent with source water — continue monitoring'] },
  },
];

// Lookup so pages can fetch the right test array by system key.
export const TESTS_BY_SYSTEM = {
  boiler: BOILER_TESTS,
  chilled: CHILLED_TESTS,
  cooling_tower: COOLING_TOWER_TESTS,
  condensate: CONDENSATE_TESTS,
  softener: SOFTENER_TESTS,
};
